sudo: require
services:
    - docker

before_install:
    - docker build -t roaslin/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true roaslin/client-test npm test

after_success:
    - docker build -t roaslin/multi-client ./client
    - docker build -t roaslin/multi-nginx ./nginx
    - docker build -t roaslin/multi-server ./server
    - docker build -t roaslin/multi-worker ./worker
    # login into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push roaslin/multi-client
    - docker push roaslin/multi-nginx
    - docker push roaslin/multi-server
    - docker push roaslin/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-north-1
    app: multi-docker-1
    env: MultiDocker1-env
    bucket_name: elasticbeanstalk-eu-north-1-300563897675
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key:
        secure: $AWS_SECRET_ACCESS_KEY


