apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config            
--- # Postgres needs that property to work due to latest version changes
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    component: configs
data:
  POSTGRES_HOST_AUTH_METHOD: trust
